In [5]:
import tkinter as tk
from tkinter import messagebox
from PIL import Image, ImageTk
import cv2
import numpy as np
import tkinter as tk
from tkinter import messagebox
from PIL import Image, ImageTk
import os

current_image_index = 0
def show_image(faces,img):
    global current_image_index
    # Initialize variables
    current_image_index = 0

    # Function to show the next image
    def show_next_image(img):
        global current_image_index
        if current_image_index < len(faces):
            face = faces[current_image_index]
            load_and_display_image(face,img)
            current_image_index += 1
        else:
            messagebox.showinfo("Finished","All images are done!")
            #root.destroy()

    # Function to load and display an image
    def load_and_display_image(face,img):
        x,y,w,h = face
        crop_img = img[y:y+h, x:x+w]
        print(crop_img)
        dim = (64, 64)
         # Crop image
        resized = cv2.resize(crop_img, dim, interpolation = cv2.INTER_AREA) 
        image1 = Image.fromarray(resized)
        #image2 = image1.resize((300, 300))  # Resize the image to fit the window
        photo = ImageTk.PhotoImage(image1)
        #cv2.imshow("photo",photo)
        #photo.show()
        image_label.config(image=photo)
        image_label.image = photo  # Keep a reference to prevent garbage collection

    # Function to handle the "Yes" button
    def answer_yes():
        show_next_image(img)

    # Function to handle the "No" button
    def answer_no():
        show_next_image(img)

    # Create the main window
    root = tk.Tk()
    root.title("Image Viewer")

    # Create a label to display the images
    image_label = tk.Label(root)
    image_label.pack()

    # Create "Yes" and "No" buttons
    yes_button = tk.Button(root, text="Yes", command=answer_yes)
    no_button = tk.Button(root, text="No", command=answer_no)
    yes_button.pack(side=tk.LEFT)
    no_button.pack(side=tk.RIGHT)

    # Show the first image
    show_next_image(img)

    # Start the Tkinter main loop
    root.mainloop()


In [6]:
face_classifier = cv2.CascadeClassifier('C:\\Users\\ravik\\Documents\\GitHub\\opencv\\data\\haarcascades\\haarcascade_frontalface_default.xml')
folder_path = "C:\\Users\\ravik\\Desktop\\My images\\test"

# Create a list to store the image file paths
image_paths = []
All_faces= []

# Loop through the files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith((".jpg", ".jpeg", ".png", ".gif", ".bmp")):
        # Add the complete file path to the list
        image_path = os.path.join(folder_path, filename)
        image_paths.append(image_path)

# To open and process the images, you can use a loop like this:
for image_path in image_paths:
    try:
        img = cv2.imread(image_path)
        #gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces= face_classifier.detectMultiScale(img, 1.3,5)
        if (len(faces)>0):            
            show_image(faces,img)
    except Exception as e:
        print(f"Error processing {image_path}: {e}")

[[[131  91  92]
  [115  75  76]
  [122  84  84]
  ...
  [238 238 238]
  [238 238 238]
  [238 238 238]]

 [[122  85  87]
  [115  81  82]
  [117  85  86]
  ...
  [238 238 238]
  [238 238 238]
  [238 238 238]]

 [[117  83  84]
  [114  82  83]
  [117  86  87]
  ...
  [238 238 238]
  [238 238 238]
  [238 238 238]]

 ...

 [[ 86  61  57]
  [ 84  59  55]
  [ 82  57  55]
  ...
  [255 251 251]
  [255 254 254]
  [246 242 241]]

 [[ 87  62  58]
  [ 83  58  54]
  [ 80  55  53]
  ...
  [228 216 214]
  [255 255 252]
  [252 247 246]]

 [[ 88  63  59]
  [ 84  59  55]
  [ 82  57  55]
  ...
  [174 161 159]
  [255 249 246]
  [255 254 254]]]
[[[255 255 254]
  [255 254 253]
  [252 250 249]
  ...
  [191 193 187]
  [191 193 187]
  [191 192 190]]

 [[239 240 238]
  [255 255 254]
  [255 255 254]
  ...
  [191 193 187]
  [192 194 188]
  [192 193 191]]

 [[ 71  72  70]
  [138 136 135]
  [181 179 178]
  ...
  [192 194 188]
  [192 194 188]
  [192 193 191]]

 ...

 [[252 253 251]
  [252 253 251]
  [252 253 251]
  ..

In [9]:
pip show numpy --version

Name: numpy
Version: 1.23.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\ravik\appdata\local\anaconda3\lib\site-packages
Requires: 
Required-by: astropy, bokeh, Bottleneck, contourpy, daal4py, datashader, datashape, gensim, h5py, holoviews, hvplot, imagecodecs, imageio, imbalanced-learn, matplotlib, mkl-fft, mkl-random, ml-dtypes, mlxtend, moviepy, numba, numexpr, opencv-python, opt-einsum, pandas, patsy, pyerfa, pymiscutils, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, statsmodels, tables, tensorboard, tensorflow-intel, tifffile, transformers, xarray
Note: you may need to restart the kernel to use updated packages.


In [ ]:
xxx